[package]
name = "ephyr"
version = "0.0.0"
edition = "2018"
authors = ["Kai Ren <tyranron@gmail.com>"]
publish = false

[profile.release]
lto = "thin"
codegen-units = 1

[dependencies]
audiopus = "0.2"
anyhow = "1.0"
byteorder = "1.3"
config = { version = "0.10", default-features = false, features = ["json"] }
derive_more = "0.99.5"
futures = { version = "0.3", features = ["compat"] }
futures-01 = { version = "0.1", package = "futures" }
hex = "0.4"
rand = "0.7"
serde = "1.0"
serde_humantime = { version = "1.0", package = "humantime-serde" }
slog = "2.5"
slog-async = "2.5"
slog-scope = "4.3"
slog-term = "2.5"
smart-default = "0.6"
structopt = "0.3"
tokio-compat = "0.1"
url = { version = "2.1", features = ["serde"] }
validator = "0.10"
validator_derive = "0.10"
[dependencies.decimal]
    version = "1.4"
    package = "rust_decimal"
    features = ["serde-float"]
[dependencies.tokio]
    version = "0.2"
    features = ["io-util", "process", "signal", "stream", "time"]
[dependencies.tokio-01]
    version = "0.1"
    package = "tokio"
[dependencies.tsclientlib]
    git = "https://github.com/ALLATRA-IT/tsclientlib"
    rev = "e39ead63c7366456b233a083bab3fc5dfa3e8bae" # branch = "changeable-hwid"
[dependencies.tsproto]
    git = "https://github.com/ALLATRA-IT/tsclientlib"
    rev = "e39ead63c7366456b233a083bab3fc5dfa3e8bae" # branch = "changeable-hwid"
[dependencies.tsproto-packets]
    git = "https://github.com/ALLATRA-IT/tsclientlib"
    rev = "e39ead63c7366456b233a083bab3fc5dfa3e8bae" # branch = "changeable-hwid"

[dev-dependencies]
serde_json = "1.0"
