[package]
name = "rtmp-mixing-poc"
version = "0.0.0"
edition = "2018"
authors = ["Kai Ren <tyranron@gmail.com>"]
publish = false

[dependencies]
audiopus = "0.2"
byteorder = "1.3"
derive_more = "0.99.5"
futures = { version = "0.3", features = ["compat"] }
futures-01 = { version = "0.1", package = "futures" }
slog = "2.5"
slog-async = "2.5"
slog-scope = "4.3"
slog-term = "2.5"
tokio = { version = "0.2", features = ["io-util", "process", "stream", "time", "fs"] }
tokio-01 = { version = "0.1", package = "tokio" }
tokio-compat = "0.1"
[dependencies.tsclientlib]
    git = "https://github.com/ReSpeak/tsclientlib"
    rev = "0205a64d66aff13ea12ad92cb8e8a11d2a322ba4" # branch = "master"
[dependencies.tsproto]
    git = "https://github.com/ReSpeak/tsclientlib"
    rev = "0205a64d66aff13ea12ad92cb8e8a11d2a322ba4" # branch = "master"
[dependencies.tsproto-packets]
    git = "https://github.com/ReSpeak/tsclientlib"
    rev = "0205a64d66aff13ea12ad92cb8e8a11d2a322ba4" # branch = "master"
