version: "2"

services:
  srs-origin:
    container_name: ephyr-srs-origin
    image: allatra/ephyr:mixer
    ports:
      - 1935:1935      # rtmp  srs-origin
      - 60001:60001    # zmq   "original" audio filter
      - 60002:60002    # zmq   "music" audio filter
    volumes:
      - ./origin.srs.conf:/usr/local/srs/conf/srs.conf:ro
      - ./example.mix.spec.json:/etc/ephyr/mix.json:ro
