name: Security audit

on:
  push:
    branches: ["**"]
    tags-ignore: ["v*"]
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
  pull_request:
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
  schedule:
    - cron: "7 7 * * *"

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
