name: Tests

on:
  push:
    branches: ["**"]
    tags-ignore: ["v*"]
    paths: ["src/**", "tests/**", "**/Cargo.toml", "**/Cargo.lock"]
  pull_request:
    paths: ["src/**", "tests/**", "**/Cargo.toml", "**/Cargo.lock"]

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          toolchain: stable
          command: test
